### ISSUE TITLE
UTF-16 records

### ISSUE THREAD

**Issue by danalex97** [danalex97/dspa#1]
Some records in the data are UTF-16, but csv's StringRecord supports only UTF-8. For now, these records are ignored and the follow error is logged:
```
Error: Error(Utf8 { pos: Some(Position { byte: 9271, line: 123, record: 122 }), err: Utf8Error { field: 2, valid_up_to: 7 } })
```

**Comment by matthewbrookes** [comment]
Rust strings are UTF-8 but probably there's some way to handle this

**Comment by danalex97** [comment]
Fixed.
